### ISSUE TITLE
nix-shell fails on missing default.nix

### ISSUE THREAD

**Issue by abathur** [willtim/Atavachron#2]

**Comment by willtim** [comment]
Thanks for pointing this out. There are currently issues with amazonka and S3 storage which have been present for 6 months, so I am moving Atavachron over to the aws package. I will fix this issue also at the same time.

**Comment by willtim** [comment]
Note also that you can generate your own default.nix from the cabal file by using cabal2nix. For example: `cabal2nix . > default.nix`
